# Use official Python base
FROM python:3.10-slim

# Install radare2 and system deps
RUN apt-get update && \
    apt-get install -y radare2 git && \
    rm -rf /var/lib/apt/lists/*

# Set workdir
WORKDIR /app

# Copy all files
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose Streamlit default port
EXPOSE 8501

# Run the app
CMD ["streamlit", "run", "app/gui.py", "--server.address=0.0.0.0", "--server.port=8501"]
